### PR TITLE
Small changes  in the mass and transmission interface

### PR DESCRIPTION
**Pull request by mpmendes**
Changed the masses to match the CAD model and the gear reduction ratios to be consistent with the technical documentation.

### CODE REVIEW

**Comment by mpmendes** [comment]
Gear reduction ratios changed to match the technical documentation of the actuators. Changed the masses to match the CAD model.

**Comment by martine1406** [comment]
The changes in kinova_description/urdf/kinova_common.xacro introduce a bug. Had the revert the pull request.

**Comment by martine1406** [comment]
prefix in undefined in kinova_description/urdf/kinova_common.xacro
also, I get the impression that we define 6 transmissions for each joint ?! This does not make much sense to me.

**Comment by mpmendes** [comment]
Introduce a bug? I guess it's possible.., I was kind of walking in "uncharted territory" while doing this :-/, but from my side I had no bugs, atleast with catkin_make

**Comment by martine1406** [comment]
where would prefix be defined in kinova_description/urdf/kinova_common.xacro? How would kinova_common.xacro know what is prefix equal to? prefix seems to be defined only in j2n6s300.xacro files and such, unless I am missing something?

Thanks

**Comment by mpmendes** [comment]
Yeah, I vaguely remember that. I think I asked myself the same thing. It was a long time ago though.
I think I added the transmission interfaces because they were somehow missing, or only detailing some joints. You are right on that the prefix I do remember was undefined on the file I thought it was being referenced through the imports

**Pull request merged**
