### PR TITLE
Complete cartesian velocity control including velocity control for the fingers

### PR DESCRIPTION
**Pull request by f371xx**
Based on 592e90fda95abe607b1ac4635829e05d92a1a525, I have added a cartesian velocity topic that includes the fingers. Whereas previously the fingers where controlled using a semi-position controlled setup, this one allows complete velocity control of both the cartesian 7 dofs, as well as all fingers. In theory, I'd like to take the title of the previous topic, as I think it is misleading. but this would probably break code somewhere else. 
A respective message type has been added and the relevant files updated. I use steps (per second? Tests say it's slower than that) as unit of velocity to be consistent with /j2n6s300_driver/out/finger_position

Also, I have removed an high firing INFO output from the previous topic subscriber.

Everything tested with a jaco2, 7DoF, Gen2

### CODE REVIEW

**Comment by jimzers** [comment]
Hey @f371xx !

Had a few questions about this commit:
1. What are the min/max velocities for `finger1`, `finger2`, and `finger3`?
2. What happens to the gripper if you keep publishing finger velocities when the fingers are already fully closed / opened?

Looking forward to your response!

**Comment by f371xx** [comment]
Hi @jimzers,
Sorry for the late reply - I wanted to verify my answers on the Jaco first.
I basically just forward the data to the internal Kinova API.

1. As mentioned above, the velocities for `fingerN` are theoretically given in _steps/second_, but my tests show them to be slower than that. I just tested running from Step 4000 to step 6000 with `finger3=10.0` in  280 seconds, ie. at a measured speed of ~7.17 steps/s. 
Regarding min: `finger3=1` makes a measureable change in steps according to `/j2n6s300_driver/out/finger_position`, but it is too slow to see. Measuring the true velocity gave me ~0.625 steps/s.
Max is a bit more complicated. I believe the max to be somewhere between `finger3=8000` and `finger3=10000`. This seems to be the default finger closing velocity that is also achieved with the joystick and closes the third finger in roughly 2 seconds, giving it a ~3600 steps/s

2. Nothing. The internal API stops any motion outside the range of the fingers. You can audibly verify that the motors are not running anymore.

I hope I could help,

Felix

**Comment by jimzers** [comment]
Hey @f371xx ,

Thanks for the heads up! Went ahead and implemented this work based on your forked repo - confirming that this velocity control works on my Kinova gen2 7DOF.

Would love to see this PR merged into the master branch!

**Comment by felixmaisonneuve** [comment]
Hi @f371xx 

This is great work.
I will merge it into our melodic-devel branch.

Thank you for your contribution
Felix

**Comment by jimzers** [comment]
Hey @felixmaisonneuve,

Was wondering if there was any concrete documentation on the max number of "steps" in the Kinova internal API for each finger - seeing as though this PR concerns feeding a velocity slightly related to the step/second measure. Let me know if such documentation exists!

**Comment by f371xx** [comment]
Hi @jimzers,

You can measure that yourself with the topic `.../out/finger_position`.

In the previous implementation however, the following was used as max value:
`float finger_max_turn = 6800.0; // position units` (see kinova_driver/src/kinova_arm.cpp Line 510),
but in my experiments I measured different (higher) values, at least for the third finger.

**Comment by felixmaisonneuve** [comment]
Hi @jimzers,

As @f371xx said, you are able to measure it yourself for your own arm with the topic `.../out/finger_position`.

6800 is the value used in the examples as the limit, but the fingers can go further (if you use the joystick for example). 
The exact limit is arbitrary and can slightly change based on the firmware version you are using if I remember correctly. There is not any documentation (that I can think of) with this information.

6800 is used because it is approximately where the 2 fingers will touch each other in a closed position. You will only see a difference for the third finger (which will possibly reach further).

I hope this answers your question,
Felix

**Pull request merged**
