### PR TITLE
Adds j2s6s200.xacro and j2s6s200_standalone.xacro

### PR DESCRIPTION
**Pull request by ferrolho**
Replaces https://github.com/Kinovarobotics/kinova-ros/pull/240 in favor of simplicity.

### CODE REVIEW

**Comment by wxmerkt** [comment]
Ping - is this good to be merged? :-)

**Comment by alexvannobel** [comment]
Ok I'll merge this, test and submit a small PR if additional modifications need to be done!

**Comment by alexvannobel** [comment]
I tested it and everything looks alright.
Note that there is no MoveIt config available for this robot, though. If you need it, you will be able to create it from the j2n6s300 MoveIt config quite easily.

Thanks for the ping! ;)

**Comment by wxmerkt** [comment]
Thank you for the quick action @alexvannobel!

**Pull request merged**
