### PR TITLE
Updated m1n6s300_mico_arm_ikfast plugin and solver.

### PR DESCRIPTION
**Pull request by TheFabbiusCorp**
As stated in issue [160](https://github.com/Kinovarobotics/kinova-ros/issues/160) some old IKFast solvers do not work with the latest robot models. This newly generated and tested IKFast solver works with the current robot model files placed in the _kinova_description_ package.

### CODE REVIEW

**Comment by nsaif-kinova** [comment]
Thank you Fabio, appreciated.

**Comment by sjhansen3** [comment]
This looks great! What did you do differently to make the solver have a higher solve rate? Also can you include the output of the IKFast solver rate test?

Here are two instructions that show you how to run these tests:

1. https://answers.ros.org/question/263925/generating-an-ikfast-solution-for-4-dof-arm/

2. https://answers.ros.org/question/196753/generating-ikfast-plugin-for-5-dof-robot/

**Comment by sjhansen3** [comment]
The key thing we should document is the outcome of this line:

openravepy.databases.inversekinematics: testik, success rate: 1.000000, wrong solutions: 0.000000, no solutions: 0.000000, missing solution: 0.036000

Which is generated from this command:

docker run -it --rm -v `pwd`:/ikfast -v `pwd`/output:/root/.openrave $DOCKER_IMAGE openrave0.9.py --database inversekinematics --robot=/ikfast/wrapper.xml --iktype=translationyaxisangle4d --iktests=1000

key part being the --iktests flag

**Comment by fabiocapasso93** [comment]
@sjhansen3 In my opinion, the problem is that the current robot description (URDF, meshes, xacro) of Kinova manipulators is not suited for calculating a closed-form solution with IKFast. First, because the solver I've generated took about one hour to compute, while typical IKFast solvers are obtained in at most 10 minutes (see [IKFast documentation](http://openrave.org/docs/latest_stable/openravepy/ikfast/#faq)). Second, the solution provided with these solvers (including Jaco 7, as far as I know, and tested) carries a "big" approximation error, in the order of 10^-3.

**Comment by sjhansen3** [comment]
I also think the mico has a fundamentally challenging IK problem and tbh the manipulability is not great. I think this comes from the non spherical wrist, while neat its not a great idea from a kinematic perspective. Did you get a chance to run the IKFast test? If this has a high solve rate (I believe the current one in kinova master has a solve rate of 50-60%)

**Comment by TheFabbiusCorp** [comment]
I'm closing this PR because it's been on stale for a long time now and its changes may be deprecated.

**Pull request closed without merging**
