### PR TITLE
Use xacro instead of xacro.py

### PR DESCRIPTION
**Pull request by ferrolho**
As documented in the wiki migration page for [noetic](https://wiki.ros.org/noetic/Migration#Use_xacro_instead_of_xacro.py).

### CODE REVIEW

**Comment by ferrolho** [comment]
In ROS noetic, running this
```
roslaunch kinova_bringup kinova_robot.launch kinova_robotType:=j2s6s200
```
leads to
```
... logging to /home/henrique/.ros/log/12f08c7a-92d0-11eb-b9c6-2dd25192086c/roslaunch-henrique-XPS-15-29085.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: Invalid <param> tag: Cannot load command parameter [robot_description]: no such command [['/opt/ros/noetic/share/xacro/xacro.py', '/home/henrique/catkin_ws/src/kinova-ros/kinova_description/urdf/j2s6s200_standalone.xacro']]. 

Param xml is <param name="robot_description" command="$(find xacro)/xacro.py $(find kinova_description)/urdf/$(arg kinova_robotType)_standalone.xacro"/>
The traceback for the exception was written to the log file
```

This PR fixes the problem.

**Comment by felixmaisonneuve** [comment]
Hi @ferrolho, 

We recently added support for ROS Noetic in the branch : https://github.com/Kinovarobotics/kinova-ros/tree/noetic-devel.
In this banch, we changed every reference to `xacro.py` to `xacro` (with other things to provide full support of every feature previously available)

I will close this PR. If we missed something or something is not working as expected, you are welcome to create an issue.

Thank you very much for your work,
Felix

**Comment by ferrolho** [comment]
Hi Felix,

Those are awesome news! I've been looking forward to use the arm on Ubuntu 20.04. I remember back in April (around the time of this PR) I tried to use the arm with ROS Noetic, but I couldn't establish a connection with `kinova_bringup`. Is this new branch already working okay-ish?

Thank you,
Henrique

**Comment by felixmaisonneuve** [comment]
Yes, everything should work fine

**Pull request closed without merging**
